### ISSUE TITLE
V9: traceback error on l10n_nl_xaf_auditfile_export 

### ISSUE THREAD

**Issue by jvOrsouw** [OCA/l10n-netherlands#147]
I get an error when trying to generate an audit file with your module. Can anyone enlighten me what is wrong with the module or the data?

Traceback (most recent call last):
....
File "/opt/odoo/enterprise/web/controllers/main.py", line 902, in _call_kw
return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 250, in wrapper
return old_api(self, *args, **kwargs)
File "/opt/odoo/openerp/api.py", line 381, in old_api
result = method(recs, args, **kwargs)
File "/opt/odoo/openerp/addons/l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py", line 123, in button_generate
'XmlAuditfileFinancieel3.2.xsd'))))
File "xmlschema.pxi", line 102, in lxml.etree.XMLSchema.init (src/lxml/lxml.etree.c:168126)
XMLSchemaParseError: Element '{http://www.w3.org/2001/XMLSchema}restriction': The content is not valid. Expected is (annotation?, (simpleType?, (minExclusive | minInclusive | maxExclusive | maxInclusive | totalDigits | fractionDigits | length | minLength | maxLength | enumeration | whiteSpace | pattern)))., line 639

**Comment by NL66278** [comment]
Difficult to say. Might be an error due to the colume of data. Does it contain a large number of transactions. Is the issue still relevant?
