### ISSUE TITLE
XAF Audit traceback when using max_record [V10]

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/l10n-netherlands#172]
Couldn't reproduce in v11, when max_records isn't set the export starts running:

```
Traceback (most recent call last):
  File "/odoo/customer/odoo/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/customer/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/customer/odoo/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/customer/odoo/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/customer/odoo/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/customer/odoo/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/odoo/customer/odoo/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/odoo/customer/odoo/addons/web/controllers/main.py", line 896, in call_button
    action = self._call_kw(model, method, args, {})
  File "/odoo/customer/odoo/addons/web/controllers/main.py", line 884, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/customer/odoo/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/odoo/customer/odoo/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/customer/community/l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py", line 95, in button_generate
    'self': self,
  File "/odoo/customer/odoo/addons/web_editor/models/ir_ui_view.py", line 26, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/odoo/customer/odoo/odoo/addons/base/ir/ir_ui_view.py", line 1063, in render
    return self.env[engine].render(self.id, qcontext)
  File "/odoo/customer/odoo/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 53, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/odoo/customer/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 248, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/odoo/customer/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 322, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0]), name)
QWebException: %d format: a number is required, not unicode
Traceback (most recent call last):
  File "/odoo/customer/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_2132_2342
  File "/odoo/customer/odoo/odoo/addons/base/ir/ir_qweb/qweb.py", line 177, in foreach_iterator
    for index, (item, value) in enumerate(enum):
  File "/odoo/customer/community/l10n_nl_xaf_auditfile_export/models/xaf_auditfile_export.py", line 153, in get_partners
    default=MAX_RECORDS))
  File "/odoo/customer/odoo/odoo/models.py", line 1516, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/odoo/customer/odoo/odoo/addons/base/res/res_partner.py", line 639, in _search
    count=count, access_rights_uid=access_rights_uid)
  File "/odoo/customer/odoo/odoo/models.py", line 4257, in _search
    limit_str = limit and ' limit %d' % limit or ''
TypeError: %d format: a number is required, not unicode

Error to render compiling AST
TypeError: %d format: a number is required, not unicode
Template: 2132
Path: /templates/t/auditfile/company/customersSuppliers/customerSupplier
Node: <customerSupplier t-foreach="self.get_partners()" t-as="p">
                <custSupID><t t-esc="p.id"/></custSupID>
                <custSupName><t t-esc="p.name" t-esc-options="{&quot;widget&quot;: &quot;auditfile.string50&quot;}"/></custSupName>
                <contact t-if="p.is_company and p.child_ids"><t t-esc="p.child_ids[0].name" t-esc-options="{&quot;widget&quot;: &quot;auditfile.string50&quot;}"/></contact>
                <telephone><t t-esc="p.phone" t-esc-options="{&quot;widget&quot;: &quot;auditfile.string30&quot;}"/></telephone>
                <fax><t t-esc="p.fax" t-esc-options="{&quot;widget&quot;: &quot;auditfile.string30&quot;}"/></fax>
                <eMail><t t-esc="p.email"/></eMail>
                <website><t t-esc="p.website"/></website>
                <!-- not in standard data model
                <commerceNr /> /-->
                <taxRegistrationCountry t-if="p.country_id"><t t-esc="p.country_id.code"/></taxRegistrationCountry>
                <taxRegIdent><t t-esc="p.vat" t-esc-options="{&quot;widget&quot;: &quot;auditfile.string30&quot;}"/></taxRegIdent>
                <custSupTp><t t-esc="'B' if p.customer and p.supplier else 'C' if p.customer else 'S' if p.supplier else 'O'"/></custSupTp>
                <!-- those need to be defined in <basics/> and are not required
                     labels might be used here
                <relationshipID>String</relationshipID>
                <custSupGrpID>String</custSupGrpID> -->
                <custCreditLimit t-if="p.customer and p.credit_limit"><t t-esc="p.credit_limit"/></custCreditLimit>
                <supplierLimit t-if="p.supplier and p.credit_limit"><t t-esc="p.credit_limit"/></supplierLimit>
                <streetAddress>
                    <streetname><t t-esc="p.street" t-esc-options="{&quot;widget&quot;: &quot;auditfile.string999&quot;}"/></streetname>
                    <number/>
                    <numberExtension/>
                    <property/>
                    <city><t t-esc="p.city" t-esc-options="{&quot;widget&quot;: &quot;auditfile.string50&quot;}"/></city>
                    <postalCode><t t-esc="p.zip" t-esc-options="{&quot;widget&quot;: &quot;auditfile.string10&quot;}"/></postalCode>
                    <region><t t-esc="p.state_id.name" t-esc-options="{&quot;widget&quot;: &quot;auditfile.string50&quot;}"/></region>
                    <country t-if="p.country_id"><t t-esc="p.country_id.code"/></country>
                </streetAddress>
                <bankAccount t-foreach="p.bank_ids" t-as="bank">
                    <bankAccNr><t t-esc="bank.acc_number"/></bankAccNr>
                    <bankIdCd><t t-esc="bank.bank_bic or bank.bank_id.bic"/></bankIdCd>
                </bankAccount>
                <changeInfo t-if="p.write_uid">
                    <userID><t t-esc="p.write_uid.login"/></userID>
                    <changeDateTime><t t-esc="p.write_date[:10]"/>T<t t-esc="p.write_date[-8:]"/></changeDateTime>
                    <changeDescription>Laast geschreven</changeDescription>
                </changeInfo>
                <customerSupplierHistory/>
            </customerSupplier>
```

**Comment by astirpe** [comment]
The fix made for V8 https://github.com/OCA/l10n-netherlands/pull/134 must be ported to V9, V10 and V11.
Working on it.

**Comment by astirpe** [comment]
This one can be closed (don't know why was not automatically closed on merge).
