### ISSUE TITLE
[BUG] l10n_nl_cbs_export: ValueError: day is out of range for month

### ISSUE THREAD

**Issue by astirpe** [OCA/l10n-netherlands#206]
The tests of module `l10n_nl_cbs_export` failed on date 31/10/2018 because of a bug in the code.
Here is the traceback from Travis:

```
ERROR: test_04_run_cron_job (odoo.addons.l10n_nl_cbs_export.tests.test_cbs_export_file.TestCbsExportFile)
Traceback (most recent call last):
`   File "/home/travis/build/OCA/l10n-netherlands/l10n_nl_cbs_export/tests/test_cbs_export_file.py", line 205, in test_04_run_cron_job
`     self.env['cbs.export.file'].cron_get_cbs_export_file()
`   File "/home/travis/build/OCA/l10n-netherlands/l10n_nl_cbs_export/models/cbs_export_file.py", line 159, in cron_get_cbs_export_file
`     cbs_export_file.export_file()
`   File "/home/travis/build/OCA/l10n-netherlands/l10n_nl_cbs_export/models/cbs_export_file.py", line 165, in export_file
`     cbs_export_data = self._format_header()
`   File "/home/travis/build/OCA/l10n-netherlands/l10n_nl_cbs_export/models/cbs_export_file.py", line 182, in _format_header
`     month=int(self.month), year=int(self.year))
` ValueError: day is out of range for month
```

Working on a patch, I'll open a PR soon.

**Comment by astirpe** [comment]
Fix merged
