### ISSUE TITLE
Postcodeapi not working

### ISSUE THREAD

**Issue by Dutchmoors** [OCA/l10n-netherlands#85]
I installed the postcode module for odoo v10 community edition.
-Module installed
-pyPostcode installed
-Dutch Provinces imported

When I enter a postcode I get the following odoo Server error:

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5494, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python2.7/dist-packages/odoo/models.py", line 5392, in _onchange_eval
    method_res = method(self)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/l10n_nl_postcodeapi/models/res_partner.py", line 75, in on_change_zip_street_number
    provider_obj = self.get_provider_obj()
  File "<string>", line 2, in get_provider_obj
  File "/usr/lib/python2.7/dist-packages/odoo/tools/cache.py", line 87, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/odoo/addons/l10n_nl_postcodeapi/models/res_partner.py", line 45, in get_provider_obj
    _('Could not verify the connection with the address '
TypeError: __init__() takes exactly 2 arguments (3 given)

**Comment by astirpe** [comment]
@Dutchmoors could you check the fix made in #86 ?

**Comment by Dutchmoors** [comment]
I'm new to github ....
The fix is that you removed:  __('error'),_ on line 44, correct?

That change results in an error message that says:
_"De verbinding met de postcodeserver kon niet gevalideerd worden (als je deze melding niet meer wilt zien, hernoem of verwijder dan de systeemparameter 'l10n_nl_postcodeapi.apikey')."_

So I still have a problem (although I do have an api-key for the system parameter), **but the system is throwing the right error message.**
